name = "adned-landing-page"
compatibility_date = "2024-01-01"

# Tu API Token de Cloudflare
# Obtén tu token en: https://dash.cloudflare.com/profile/api-tokens
# Crea un token con permisos de "Cloudflare Pages:Edit"
# api_token = "tu_api_token_aqui"

[env.production]
name = "adned-landing-page"

[env.preview]
name = "adned-landing-page-preview"

# Build configuration
[build]
command = "npm run build"
cwd = "."

# Pages configuration
[[pages_builds]]
build_output_dir = ".svelte-kit/cloudflare"
